// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaUIzOEJtpekI-4nFYrvDRYa39ADBttR0',
    appId: '1:536966046543:web:ba28fed03e26207b2a1b3a',
    messagingSenderId: '536966046543',
    projectId: 'farm-management-de6d9',
    authDomain: 'farm-management-de6d9.firebaseapp.com',
    storageBucket: 'farm-management-de6d9.firebasestorage.app',
    measurementId: 'G-GGQBE106H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbaYD9c8ZZDxxybNM0NsIMXUqu2E5egJA',
    appId: '1:536966046543:android:003871189c84849f2a1b3a',
    messagingSenderId: '536966046543',
    projectId: 'farm-management-de6d9',
    storageBucket: 'farm-management-de6d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm5HUxISY0pdav0jQCjzZMp9_Yr-k4wSM',
    appId: '1:536966046543:ios:a8afcde47ec55d202a1b3a',
    messagingSenderId: '536966046543',
    projectId: 'farm-management-de6d9',
    storageBucket: 'farm-management-de6d9.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm5HUxISY0pdav0jQCjzZMp9_Yr-k4wSM',
    appId: '1:536966046543:ios:a8afcde47ec55d202a1b3a',
    messagingSenderId: '536966046543',
    projectId: 'farm-management-de6d9',
    storageBucket: 'farm-management-de6d9.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaUIzOEJtpekI-4nFYrvDRYa39ADBttR0',
    appId: '1:536966046543:web:108a342681817a512a1b3a',
    messagingSenderId: '536966046543',
    projectId: 'farm-management-de6d9',
    authDomain: 'farm-management-de6d9.firebaseapp.com',
    storageBucket: 'farm-management-de6d9.firebasestorage.app',
    measurementId: 'G-07G1Y6EGLW',
  );
}
